In [65]:
import numpy as np

In [66]:
list = [0,1,2,3,4,5,6,7]
list

[0, 1, 2, 3, 4, 5, 6, 7]

In [67]:
length = len(list)

In [69]:
length == 9

False

In [70]:
try:
    if (length == 9): # Following use of reshape needs length of exact 9 numbers
        array = np.asarray(list)
except:
    print("List must contain nine numbers.")

In [71]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
mat = np.reshape(array, (3,3))
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
'mean': [axis1, axis2, flattened],
  'variance': [axis1, axis2, flattened],
  'standard deviation': [axis1, axis2, flattened],
  'max': [axis1, axis2, flattened],
  'min': [axis1, axis2, flattened],
  'sum': [axis1, axis2, flattened]

SyntaxError: illegal target for annotation (4035288433.py, line 1)

In [74]:
meanax1 = np.mean(mat, axis=0)
meanax2 = np.mean(mat, axis=1)
meanfl = np.mean(mat)
print(meanax1, meanax2, meanfl)

[3. 4. 5.] [1. 4. 7.] 4.0


In [75]:
varax1 = np.var(mat, axis=0)
varax2 = np.var(mat, axis=1)
varfl = np.var(mat)
print(varax1, varax2, varfl)

[6. 6. 6.] [0.66666667 0.66666667 0.66666667] 6.666666666666667


In [76]:
stdax1 = np.std(mat, axis=0)
stdax2 = np.std(mat, axis=1)
stdfl = np.std(mat)
print(stdax1, stdax2, stdfl)

[2.44948974 2.44948974 2.44948974] [0.81649658 0.81649658 0.81649658] 2.581988897471611


In [77]:
maxax1 = np.max(mat, axis=0)
maxax2 = np.max(mat, axis=1)
maxfl = np.max(mat)
print(maxax1, maxax2, maxfl)

[6 7 8] [2 5 8] 8


In [78]:
minax1 = np.min(mat, axis=0)
minax2 = np.min(mat, axis=1)
minfl = np.min(mat)
print(minax1, minax2, minfl)

[0 1 2] [0 3 6] 0


In [79]:
sumax1 = np.sum(mat, axis=0)
sumax2 = np.sum(mat, axis=1)
sumfl = np.sum(mat)
print(sumax1, sumax2, sumfl)

[ 9 12 15] [ 3 12 21] 36


In [80]:
sumax1.tolist()

[9, 12, 15]

In [88]:
meanax1 = np.mean(mat, axis=0).tolist()
meanax2 = np.mean(mat, axis=1).tolist()
meanfl = np.mean(mat).tolist()

varax1 = np.var(mat, axis=0).tolist()
varax2 = np.var(mat, axis=1).tolist()
varfl = np.var(mat).tolist()
    
stdax1 = np.std(mat, axis=0).tolist()
stdax2 = np.std(mat, axis=1).tolist()
stdfl = np.std(mat).tolist()
    
maxax1 = np.max(mat, axis=0).tolist()
maxax2 = np.max(mat, axis=1).tolist()
maxfl = np.max(mat).tolist()
    
minax1 = np.min(mat, axis=0).tolist()
minax2 = np.min(mat, axis=1).tolist()
minfl = np.min(mat).tolist()
    
sumax1 = np.sum(mat, axis=0).tolist()
sumax2 = np.sum(mat, axis=1).tolist()
sumfl = np.sum(mat).tolist()

In [82]:
calculations = {
      'mean': [meanax1, meanax2, meanfl],
      'variance': [varax1, varax2, varfl],
      'standard deviation': [stdax1, stdax2, stdfl],
      'max': [maxax1, maxax2, maxfl],
      'min': [minax1, minax2, minfl],
      'sum': [sumax1, sumax2, sumfl]
}
calculations

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [89]:
type(sumfl)

numpy.int64

In [1]:
%run main.py

...
----------------------------------------------------------------------
Ran 3 tests in 0.006s

OK


{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}
